# Generated by Django 5.1.2 on 2024-10-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0002_alter_hotel_hotel_banner_alter_hotel_interior_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ads_image', models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='ads_image')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='picked_of_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='top_ten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_banner',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_image'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='interior_image',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='hotel_image'),
        ),
    ]
