# Generated by Django 5.1.2 on 2024-10-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0003_adsslide_hotel_picked_of_day_room_top_ten_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.FileField(blank=True, default='no_image/noimage.png', null=True, upload_to='room_images/'),
        ),
    ]
