# Generated by Django 5.1.2 on 2024-10-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0005_siteasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteasset',
            name='instagram_icon',
            field=models.ImageField(blank=True, default='no_image/noimage.png', null=True, upload_to='social_media/'),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='twitter_icon',
            field=models.ImageField(blank=True, default='no_image/noimage.png', null=True, upload_to='social_media/'),
        ),
    ]
