# Generated by Django 5.1.2 on 2024-10-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StayfinderApp', '0006_alter_siteasset_instagram_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteasset',
            name='logo',
            field=models.ImageField(blank=True, default='no_image/noimage.png', null=True, upload_to='logos/'),
        ),
    ]
